### ISSUE TITLE
Education Evidences Errata - relationship "has supplement" lacks of consistency between diploma evidence and the others

### ISSUE THREAD

**Issue by XHochschuleDE** [SEMICeu/SDG-sandbox#150]
The information on diploma and diploma supplement are not streamlined in the various diagrams and tables for diploma, diploma supplement and record of results.

Example:

Diploma supplement currently has a "is supplement of" relationship to the diploma 
in the diploma supplement and in the record of results  [table ](https://github.com/SEMICeu/SDG-sandbox/blob/master/evidences/tertiary_education_diploma_supplement_evidence/data_model/tertiary_education_diploma_supplement_evidence_tables_v0.02.md)
but "has supplement" relationship from diploma to supplement in the diploma [diagramm](https://github.com/SEMICeu/SDG-sandbox/blob/master/evidences/tertiary_education_diploma_evidence/data_model/tertiary_education_diploma_evidence_diagram_v0.02.png)

![image](https://user-images.githubusercontent.com/72596288/98220237-4aeeb480-1f4e-11eb-84af-e7760bc258e7.png)

vs.

![image](https://user-images.githubusercontent.com/72596288/98220637-df591700-1f4e-11eb-9b61-70e9a05a8716.png)

This issue was handed in by [XHochschule](https://www.youtube.com/watch?v=RGzclgtpnWA) but was found by CaMs manufacturer HIS eG in the [2nd German call for comments](http://www.xhochschule.de/web/sdg_comments_round2#issuesRelationshipsInDiagrammeButNotInTable)

**Comment by cbahim** [comment]
@XHochschuleDE thanks for you comment. This is made on purpose. Currently, all three evidences are alike except for the relationships from one to another.

So, as you are pointing out, the diploma has the relationship `hasSupplement` to the diploma supplement, while conversly the diploma evidence has the relationship `isSupplementOf` to the diploma supplement evidence. 

Please let us know if you think otherwise.
