### ISSUE TITLE
VehicleRegistrationCertificate evidence should contain registration status

### ISSUE THREAD

**Issue by roefie64** [SEMICeu/SDG-sandbox#16]
In the VehicleRegistration evidence in the current design there is no place to indicate what the status of the registration is. It should be possible to indicate that a vehicle is registered to be stolen, scrapped or may not be exported (like hired/ leased cars). This is very relevant when registering a vehicle in another country.

**Comment by cbahim** [comment]
Thanks for your comment @roefie64 

See also issue #15 

We propose to add the optional attribute *status* to the Vehicle Registration class, with definition 

> The status of a vehicle or vehicle registration related circumstance or qualification, that normally emerged after registration of the vehicle. A signal/status may be temporary or definite.

We propose to use the list from annex E of the [EUCARIS VAT XSD](https://github.com/SEMICeu/SDG-sandbox/files/4931485/EUCARIS.XML.Message.Specification.VAT.pdf) as controlled vocabulary for this attribute. Below we give an overview of the possible statuses with their definition. For more information, we refer to the annex.

- Vehicle stolen: Vehicle has been reported stolen or missing by the police, insurance companies or other sources.
- Vehicle exported: Vehicle has been de-registered in the Member State, because of export. The signal also indicates that the vehicle is now registered in another country.
- Vehicle registration cancelled due to destruction: Vehicle has been reported end-of-life in accordance with Directive 2000/53/EC. The authorisation for the vehicle to be used in road traffic has been cancelled permanently.
- Vehicle de-registered: Termination of the registration for unspecified reasons.
- Duplicate vehicle registration certificate issued: This signal can be used if after loss, theft or severe damage to the vehicle registration certificate, this has been replaced by a new document, or a copy with the same document number.
- Vehicle seriously damaged: The vehicle was seriously damaged in an accident or was reported to have dangerous defects at an inspection.
- Registration suspended: The authorisation for the vehicle to be used in road traffic is suspended for a limited period of time following which – provided the reasons for suspension have ceased to apply – it may be authorised to be used again, without involving a new process of registration.
- Vehicle registration certificate stolen: Vehicle registration certificate has been reported stolen or missing by the police or other sources.
- Vehicle registration plates stolen: Vehicle registration plate has been reported stolen or missing by the police or other sources.
- Re-registration blocked: Re-registration blocked for various administrative reasons.

@roefie64 and others, do we only want to provide the current, active status or also keep a history of previous statuses?

**Comment by roefie64** [comment]
The history of the vehicle status should be kept in a member state since it is used for criminal and fraud investigations. For the VehicleRegistrationEvidence only the actual status should be exchanged.

**Comment by cbahim** [comment]
@roefie64 since no member states expressed the same needs, we will leave this attribute out of the model.

**Comment by cbahim** [comment]
Correction: the threshold has been reached so this attribute will be included.
