### ISSUE TITLE
Absence of a criminal record (PT)

### ISSUE THREAD

**Issue by ama-epse** [SEMICeu/SDG-sandbox#182]
Depending on purpose, certain aspects of criminal record might not be relevant or cannot be provided, therefore the PT domain expert commented that the evidence cannot be produced if purpose is not provided in advance.

There must be a purpose statement in order to produce this type of evidence, for legal and privacy reasons.

**Comment by ikolar** [comment]
This is true:

- a criminal record for the purpose of criminal or administrative proceedings (eg. before a court) will usually be negative if the person has no convictions in the criminal registry (straightforward case);
- a record for the purpose of obtaining a job, or applying to a public tender, could still be negative if the person has certain convictions (ie. minor convictions or convictions not relevant to the tender process) in the regisry;
- on the other hand, a record for the purpose of working with children would still be positive if the person not longer has convictions in the criminal registry, but had (a long time ago) been convicted for certain crimes, ie. sexual exploitation of children, than have since been expunged from the registry.

To allow for this, you need to add a "purpose" attribute to the document.

A list of purposes can be obtained from the ECRIS system.

**Comment by EmielDh** [comment]
Thank you for your interest and contribution. Please note that this GitHub space is currently not updated (will be soon deprecated), and similar inputs and requests are now handled by the OOTS Helpdesk.

For your information, the current approach for SDG OOTS aims at the reuse of existing data models (where possible) and systems as a possible vehicle for OOTS evidence exchange.

For more information and to stay up-to-date with OOTS developments please consult the recently launched [Once Only Hub ](https://ec.europa.eu/digital-building-blocks/wikis/display/OOTS/OOTSHUB+Home)or reach out to the [OOTS Helpdesk](https://ec.europa.eu/digital-building-blocks/tracker/plugins/servlet/desk/portal/15).
