### ISSUE TITLE
Marriage certificate: (optional) witnesses ?

### ISSUE THREAD

**Issue by barthanssens** [SEMICeu/SDG-sandbox#19]
Not a subject expert, but some countries require witnesses to be present at the wedding (and also note down the names of those witnesses).
I assume this information is not required for cross-border exchange of marriage certificates ? Would it be useful to have the possibility to add [0..n] witnesses, or would this be overkill ?

**Comment by sethvanhooland** [comment]
Good question Bart. It would be good to hear from domain experts which countries do or do not include this within their models, either as optional or obligatory. My guess would be we could include it in the optional elements a MS can use to extend the application profile.

**Comment by tomayac** [comment]
It’s optional to nominate up to two groomsmen in Germany: gesetze-im-internet.de/bgb/__1312.html.

**Comment by sethvanhooland** [comment]
Thanks for clarifying us on the situation in Germany Tom!

**Comment by giorgialodi** [comment]
Hi all, I am not really expert of certificates, however, looking at some Italian laws and Municipalities' institutional web sites, the situation is more or less as follows. When you get married, the marriage is registered in a so-called "marriage act" that contains all info, even the name, surname, place and birth date and residency of the witnesses. In the marriage certificate, this info seems not present because the role of the certificate should be to demonstrate the date and place of the marriage happened between two persons (whose names are in the certificate) . People can ask for so called "extracts per summary of the marriage act" where additional info (they call it "annotations") wrt the certificate can be included (e.g, the patrimonial regime of the spouses, citizenship). Besides this, it is possible to have a copy of the marriage act with the detailed info.  In essence, it seems to me that this information is not mandatory for our country in the marriage certificates.

**Comment by pfragkou** [comment]
I agree with Giorgia. The same holds in Greece, both for civil as well as chiurch marriages. When you get married, the marriage is registered in a so-called "marriage act" that contains all info, even the name, surname, place and birth date and residency of the witnesses. In the marriage certificate, this info seems not present because the role of the certificate should be to demonstrate the date and place of the marriage happened between two persons (whose names are in the certificate) . The marriage certificate does not mention neither the witness data.

**Comment by ibodor** [comment]
**Ingrid (FIN):** in Finland (at least) two witnesses must be present/testify/sign but no data of these persons are in the digital marriage certificate issued by the competent authority.

**Comment by cbahim** [comment]
Thank you all for your contribution, looking at the above points we don't think it is necessary to include the witnesses in the marriage evidence.
