### ISSUE TITLE
Code lists for addresses

### ISSUE THREAD

**Issue by andrea-perego** [SEMICeu/SDG-sandbox#29]
I don't know if this option has been already discussed, but for address information concerning administrative units, using the NUTS codes would help interoperability. 

Notably, an RDF representation of the NUTS has also been published by EUROSTAT, so NUTS URIs are also available:

https://ec.europa.eu/eurostat/web/nuts/linked-open-data

This RDF representation is available as Linked Data via the EU Vocabularies service:

https://op.europa.eu/en/web/eu-vocabularies/at-dataset/-/resource/dataset/nuts

E.g.: http://data.europa.eu/nuts/code/ITC4C

About postal codes, EUROSTAT maintains correspondence tables with the different versions of the NUTS, which could be useful to automatically infer the relevant NUTS codes:

https://ec.europa.eu/eurostat/web/nuts/correspondence-tables/postcodes-and-nuts

**Comment by sethvanhooland** [comment]
Thanks Andrea for your contribution! The NUTS URIs are indeed a valuable new resource, which has recently been included for example in the Kohesio.eu project, which SEMIC is involved in. A Wikibase put up for DG REGIO with the help of colleagues from CNECT, available on https://linkedopendata.eu/wiki/The_EU_Knowledge_Graph includes since last week the NUTS property, e.g. https://linkedopendata.eu/wiki/Item:Q74781. 

We can discuss during the next webinar how we could leverage NUTS for the SDG data models.

**Comment by barthelemyf** [comment]
Please note that, as part of the repository of links (information to be provided together with the links to the national/regional webpages), the current proposition is to use ISO codes for locations.
