### ISSUE TITLE
Income tax declaration certificate: paymentDate to taxYear

### ISSUE THREAD

**Issue by cbahim** [SEMICeu/SDG-sandbox#67]
A proposition was made in #39 to rename `paymentDate` to `taxYear`, i.e. the year to which the tax declaration refers. However, this does not appear to contain the same information as the payment date. We therefore ask from the MS to (1) provide input on the relevance of the payment date and (2) to give feedback on the addition of the tax year attribute.

**Comment by thodoris** [comment]
We agree with ES and IT. 
In our case (GR) , a tax declaration certificate does not contain any paymentDate field. 
The payment of the taxes happens in a much later stage of the income taxation process.

According to the definition of the tax declaration certificate

> Definition: Official document in which **a Tax Payer declares** the Monetary Amount that he or she has earned and the taxes that he or she has paid in one year.

, the tax declaration certificate is what the tax payer declares. Ususally the revenue/taxing authorities do not rely solely on this declaration of the tax payer in order to calculate the correct amount of tax that he/she should pay. So in our view, the paymentDate attribute is irrelevant and should be removed.

In the case of Greece the workflow for income taxation is as follows:
1. The tax payer submits his/her **tax declaration form**  (form not certificate). 
2. The competent authority (tax authority) issues a **tax clearance certificate** (“ekkatharistiko” in Greek), which contains the final/official income tax that must be paid. 
3. The tax payer pays the income tax 
4. The tax authority then issues (upon request)  a  **Proof of tax clearance**  (“forologiki enimerotita” in Greek), which verifies that the taxes for the previous taxYear has been paid and there are no due payments.  But this document does not contain any information about payment dates. 

Concluding, we would propose to remove  paymentDate  and introduce a new attribute taxYear (with a new description clearly indicating that it conserns the fiscal year of reference of the income tax declaration).

**Comment by anarosa-es** [comment]
We agree on the workflow described by GR.

We currently provide two data services to be consumed by administrative procedures outside the taxation domain. 

One of them provides the **income level** corresponding to a specific citizen as result of his/her tax declaration at a specific tax year. How exactly this income level is calculated depends on the fiscal year because tax regulation may differ slightly each year.

The second data service tells wheter a specific citizen is **up to date with the tax obligations of the last closed fiscal year**, in general or in particular for public contracts, transport permits, receiving public assistance/subsidies, or work/residence permits.
