### ISSUE TITLE
Input from DG TAXUD

### ISSUE THREAD

**Issue by guascce** [SEMICeu/SDG-sandbox#70]
Thank you for requesting our input on the linguistic aspects of the income tax declaration certification to be used for the SDG.

We have inserted a few formalistic suggestions, as well as suggested to add a few fields (see document attached).

However, as already discussed, we have some doubt about the usefulness of putting such information on the SDG. Indeed, we do not see, at first sight, and from the perspective of the Member States’ tax administrations, to what purpose this information could be used.

Maybe it would be worth discussing this in more detail with colleagues from DG GROW. For e.g. we would see the tax residence certificate, which is often requested by tax administrations of various States to grant tax benefits to the taxpayer, as a more suited candidate for the SDG.

Could you please keep us informed of the procedure?

We stay at your disposal if you need further information.

Best regards,

Charlotte Delsol

[Income tax declaration.docx](https://github.com/SEMICeu/SDG-sandbox/files/5074751/Income.tax.declaration.docx)

**Comment by thodoris** [comment]
Regarding the usefulness of including the income tax declaration certificate on the SDG, I think that this is provided in Annex II of the SDG regulation, therefore there is no formal/legal way to consider its substitution with a different certificate (e.g tax residence).

**Comment by anarosa-es** [comment]
For me it is clear that Annex II includes a list of administrative procedures to be provided fully online; it is not a list of evidences to exchange through the technical system.

The tax declaration certificate was proposed by Deloitte as a result of their data mapping study, if I am not wrong. I guess that Annex II procedures to apply for a study grant require the applicant's lastest income level. However, some countries may not need such information from another Member State because an usual precondition is to reside in the national territory since 1 or 2 years to be eligible for these grants.

So I agree with Charlotte that proof of residence is probably more requested for processing Annex II procedures than tax declaration in a cross-border context (i.e. the proof is provided by a different country than the one processesing the procedure).
