### ISSUE TITLE
Marriage certificate (CZ)

### ISSUE THREAD

**Issue by psiotwo** [SEMICeu/SDG-sandbox#99]
Marriage certificate issues
1. In the Czech Republic a marriage certificate is only issued in the case of couples of the opposite sex. For same sex couples it is possible to enter into a registered partnership, which is certified by the Registered partnership certificate.
2. A person who is married cannot enter into a new marriage. Thus, the marital status before marriage can only be single, divorced or widowed. Perhaps the term ‘previously married’ may be more suitable than ‘married’.
3. The citizenship of a person is not mentioned in the Czech marriage certificate.

**Comment by cbahim** [comment]
Thanks @psiotwo for your comments. 

> In the Czech Republic a marriage certificate is only issued in the case of couples of the opposite sex. For same sex couples it is possible to enter into a registered partnership, which is certified by the Registered partnership certificate.

If we understand correctly the marriage and registered partnership are two different types of evidences, therefore we don't see a problem with our current model. Let us know if otherwise. 

> A person who is married cannot enter into a new marriage. Thus, the marital status before marriage can only be single, divorced or widowed. Perhaps the term ‘previously married’ may be more suitable than ‘married’.

For the `maritalStatus` we use the [Marital Status table](https://op.europa.eu/en/web/eu-vocabularies/th-concept/-/resource/eurovoc/4184) which contains the statuses you mentioned.  

> The citizenship of a person is not mentioned in the Czech marriage certificate.

This does not pose a problem as `citizenship` is marked optional in the model.
